# Generated by Django 4.0.4 on 2022-04-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='self/')),
                ('heading', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('award', models.IntegerField()),
                ('hours_worked', models.IntegerField()),
                ('project_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showcase_image', models.ImageField(upload_to='img/')),
                ('header_content', models.CharField(max_length=200)),
                ('specialize_content', models.CharField(max_length=250)),
                ('specialist_title', models.CharField(max_length=200)),
                ('specialist_summary', models.CharField(max_length=800)),
                ('section_title', models.CharField(max_length=100)),
                ('section_content', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Process_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialize_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_words', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Specialize_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('comment', models.TextField()),
                ('section_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_4', to='my_portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('section_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_2', to='my_portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Logo_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('section_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_3', to='my_portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Award_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AWARD ONE', max_length=20)),
                ('details', models.CharField(max_length=250)),
                ('section_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_1', to='my_portfolio.about')),
            ],
        ),
    ]
