# Generated by Django 4.1 on 2022-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_remove_work_category_achievement_section_section_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='award',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='hours_worked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='project_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Achievement_section',
        ),
    ]
