# Generated by Django 4.1 on 2022-12-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_home_award_home_client_home_hours_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award_section',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award_section',
            name='title',
            field=models.CharField(blank=True, default='AWARD ONE', max_length=100, null=True),
        ),
    ]
